base/the_usual_weather/forms.py
from flask_wtf import FlaskForm
from geopy.geocoders import Nominatim
#from base.models import weather model
from wtforms import (StringField,
                     SubmitField,
                     IntegerField,
                     ValidationError,
                     DateField)
from wtforms.validators import DataRequired, EqualTo, length
from base.lumberjack.views import lumberjack_do
from base.users.views import current_user
from datetime import datetime



class WeatherSubmitForm(FlaskForm):
    city = StringField('City', validators=[DataRequired(), length(max=30)])
    date = DateField('Date', validators=[DataRequired()])
    submit = SubmitField('Submit')

    def validate_city(self, field):
        # if city is valid, then it needs to also generate GPS coordinates for the submission
        location = Nominatim(timeout=10000, user_agent="Geopy Library")
        get_location = location.geocode(field.data)
        try:
            lat = round(float(get_location.latitude), 5)
            long = round(float(get_location.longitude), 5)
            # print(lat, long)
            #storing lat & long so we don't have to redo this
            self.latitude = lat
            self.longitude = long
        except AttributeError:
            lumberjack_do(datetime.utcnow(), current_user, "the usual weather", {"type": "Invalid City", 'Submitted City': field.data})
            raise ValidationError('Invalid city name. Please check your spelling and try again.')
        location_details = location.reverse((lat, long))
        location_details_raw = location_details.raw
        #since city names are not unique, we should reverse lookup the coordinates to give a more descriptive location
        #need to account for non-english characters in the names
        try:
            self.decoded_city = location_details_raw['address']['city']
        except:
            self.decoded_city = "City not found - possibly an unincorporated location or other anomalous location"
        try:
            self.decoded_state = location_details_raw['address']['state']
        except:
            self.decoded_state = "State not found - possibly a federal territory or other anomalous location"
        try:
            self.decoded_country_code = location_details_raw['address']['country_code']
        except:
            self.decoded_country_code = "Is this Antarctica? I haven't tested for Antarctica."

base/the_usual_weather/views.py
from datetime import datetime
from os import getcwd
from flask import Flask, Blueprint, render_template, request, session, redirect, url_for, flash
import json, random, markdown, uuid
from flask_login import login_required, current_user
from base import db
from base.decorators import admin_required
from base.lumberjack.views import lumberjack_do
from base.models import WeatherRequest, User
from base.the_usual_weather.forms import WeatherSubmitForm


cwd = getcwd()

the_usual_weather_blueprint = Blueprint('the_usual_weather', __name__, template_folder='templates/the_usual_weather')

@the_usual_weather_blueprint.route('/')
def the_usual_weather():
    with open (f'{cwd}/the_usual_weather/data/about.txt', 'r') as f:
        md_about = f.read()
        f.close()
        about = markdown.markdown(md_about)
    return render_template('the_usual_weather_home.html', about=about)

@the_usual_weather_blueprint.route('/submit', methods=['GET', 'POST'])
@login_required
def submit():
    form = WeatherSubmitForm()
    if form.validate_on_submit():
        # log it just in case
        job_id = str(uuid.uuid4())
        lumberjack_do(datetime.utcnow(), current_user, "the usual weather", {"type": "Submission",
                                                                             'User-Submitted city': form.city.data,
                                                                             'GPS Coordinates': str((form.latitude,
                                                                                                 form.longitude)),
                                                                             'Decoded City': form.decoded_city,
                                                                             'Decoded State': form.decoded_state,
                                                                             'Decoded Country Code': form.decoded_country_code,
                                                                             'job_id': job_id,
                                                                             'date': form.date.data})
        #commit to database
        weather_request = WeatherRequest(requesting_user=current_user.id,
                                         requested_month=form.date.data.month,
                                         requested_day=form.date.data.day,
                                         submitted_date=datetime.utcnow(),
                                         submitted_city=form.city.data,
                                         gps_coordinates=str((form.latitude, form.longitude)),
                                         decoded_city=form.decoded_city,
                                         decoded_state=form.decoded_state,
                                         decoded_country=form.decoded_country_code,
                                         job_id=job_id,
                                         job_status="Pending"
                                         )
        db.session.add(weather_request)
        db.session.commit()
        flash("Thanks for your submission!", "success")
        return redirect(url_for('the_usual_weather.report_detail', job_id=job_id))
    if form.errors:
        for field, errors in form.errors.items():
            for error in errors:
                flash(f"{field} error: {error}", "warning")
    return render_template('the_usual_weather_submit.html', form=form)


@the_usual_weather_blueprint.route('/report-list', methods=['GET'])
@login_required
def report_list():
    #get submitted jobs and shows progress
    #auto-refresh
    raw_list = db.session.execute(
        db.select(WeatherRequest).order_by(WeatherRequest.submitted_date.desc())
    ).scalars()
    pretty_list = [weather_request.to_dict() for weather_request in raw_list]
    #need a user class method for getting username by id
    for report in pretty_list:
        username = db.session.execute(db.select(User.username).filter_by(id=report['requesting_user'])).scalar_one()
        report['requesting_user'] = str(username)
    #we need to refresh the page every few minutes
    return render_template('the_usual_weather_report_list.html', pretty_list=pretty_list)

@the_usual_weather_blueprint.route('/report-detail/<job_id>', methods=['GET'])
@login_required
def report_detail(job_id):
    # takes a <job id> in the URL and returns the results
    #<job id> = weather_request.id

    #will need a new table in the db for saving/loading the API results

    # let's start by just loading a page with the request  as "pending, please refresh to check status"
    # this starts the job
    # when the job is done, you see results during a refresh

    #we need a method for checking if any jobs have been submitted and running them.
    # Maybe we just redirect here and conditionally run the job if it hasn't already been run
    #page should auto-refresh every 30 sec while job is incomplete
    report = db.session.execute(db.select(WeatherRequest).filter_by(job_id=job_id)).scalar()
    report_request = report.to_dict()
    # need a user class method for getting username by id
    username = db.session.execute(db.select(User.username).filter_by(id=report_request['requesting_user'])).scalar_one()
    report_request['requesting_user'] = str(username)
    if report_request['job_status'] != "Complete":
        #start job
        return render_template('the_usual_weather_report_detail.html',
                               report_request=report_request)
    else:
        #fetch the report and get it prepared for display
        return render_template('the_usual_weather_report_detail.html',
                               report_request=report_request,
                               report=report)


#admin function:
#Remove old results - must remove both the request and the results at the same time.
@the_usual_weather_blueprint.route('manage-reports', methods=['GET', 'POST'])
@login_required
@admin_required
def manage_reports():
    #functionality needed
    #adjust speed to avoid hitting call limits (build delay between calls and set it here)
    #suspend all job processing
    #fail a specific job
    pass

base/the_usual_weather/templates/the_usual_weather/the_usual_weather-base.html
{% extends "base.html" %}

{% block title %}
    <title>Alex's Toolbox - The Usual Weather</title>
{% endblock %}
{% block additional_css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/the_usual_weather/the_usual_weather.css') }}" />
{% endblock %}

{% block body_class %}the_usual_weather-pages{% endblock %}

<!-- I should make a tool-level navbar

base/the_usual_weather/templates/the_usual_weather/the_usual_weather_home.html
{% extends "the_usual_weather-base.html" %}

{% block content %}
    <div class="default-container">
        <h1>The Usual Weather</h1>
        <p><strong>Submit a new request <a href="{{ url_for('the_usual_weather.submit') }}">here!</a></strong></p>
        <p><strong>See past reports <a href="{{ url_for('the_usual_weather.report_list') }}">here</a></strong></p>
        <p><a href="https://github.com/AlexB-623/WeatherAnalysisApp" target="_blank">Original Project On Github</a></p>
        <p>{{ about|safe }}</p>
    </div>
{% endblock %}

base/the_usual_weather/templates/the_usual_weather/the_usual_weather_report_detail.html
{% extends "the_usual_weather-base.html" %}

{% block content %}
    <div class="default-container">
        <h1 class="tool-home"><a href="{{ url_for('the_usual_weather.the_usual_weather') }}">The Usual Weather</a> </h1>
        <h3>Report Record</h3>
        <div class="job-record">
            <div class="job-record-details">
                <table class="job-details">
                <tr>
                    <td>Requested by:</td>
                    <td>{{ report_request['requesting_user'] }}</td>
                </tr>
                <tr>
                    <td>Date Submitted:</td>
                    <td>{{ report_request['submitted_date'] }}</td>
                </tr>
                <tr>
                    <td>Requested Month-Day:</td>
                    <td>{{ report_request['requested_date'] }}</td>
                </tr>
                <tr>
                    <td>Submitted City:</td>
                    <td>{{ report_request['requested_city'] }}</td>
                </tr>
                <tr>
                    <td>Decoded Location (Map Link):</td>
                    <td><a href="https://www.google.com/maps/place/{{ report_request.gps_coordinates }}" target="_blank">
                        {{ report_request['decoded_city'] }},
                        {{ report_request['decoded_state'] }},
                        {{ report_request['decoded_country'] }},<br>
                        {{ report_request['gps_coordinates'] }}</a>
                    </td>
                </tr>
            </table>
            </div>
            <div class="job-record-status">
                <table class="job-status">
                    <tr>
                        <td>Report ID:</td>
                        <td>{{ report_request['job_id'] }}</td>
                    </tr>
                    <tr>
                        <td>Report Status:</td>
                        <td class="report-is-{{ report_request['job_status'] }}">{{ report_request['job_status'] }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

base/the_usual_weather/templates/the_usual_weather/the_usual_weather_report_list.html
{% extends "the_usual_weather-base.html" %}

{% block content %}
    <div class="report-display">
        <h1 class="tool-home"><a href="{{ url_for('the_usual_weather.the_usual_weather') }}">The Usual Weather</a> </h1>
        <p><strong>Submit a new request <a href="{{ url_for('the_usual_weather.submit') }}">here!</a></strong></p>
    <p>List of prior submissions:</p>
    <table class="report-table">
        <thead>
            <tr>
                <th>Requested By</th>
                <th>Submission Date</th>
                <th>Submission City</th>
                <th>Requested Month-Day</th>
                <th>GPS Coordinates - Map Link</th>
                <th>Decoded City</th>
                <th>Decoded State</th>
                <th>Country Code</th>
                <th>Report Status</th>
            </tr>
        </thead>
        <tbody>
        {% for report in pretty_list %}
            <tr>
                <td>{{ report.requesting_user }}</td>
                <td>{{ report.submitted_date }}</td>
                <td>{{ report.requested_city }}</td>
                <td>{{ report.requested_date }}</td>
                <td><a href="https://www.google.com/maps/place/{{ report.gps_coordinates }}" target="_blank">{{ report.gps_coordinates }}</a> </td>
                <td>{{ report.decoded_city }}</td>
                <td>{{ report.decoded_state }}</td>
                <td>{{ report.decoded_country }}</td>
                <td class="report-is-{{ report.job_status }}"><a href="{{ url_for('the_usual_weather.report_detail', job_id=report.job_id) }}">{{ report.job_status }}</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
{% endblock %}

base/the_usual_weather/templates/the_usual_weather/the_usual_weather_submission.html
{% extends "the_usual_weather-base.html" %}

{% block content %}
    <div class="the_usual_weather-container">
        <h1>The Usual Weather</h1>
        <p>Submission form here</p>
    </div>
{% endblock %}

base/the_usual_weather/templates/the_usual_weather/the_usual_weather_submit.html
{% extends "the_usual_weather-base.html" %}

{% block content %}
    <div class="default-container">
        <h1 class="tool-home"><a href="{{ url_for('the_usual_weather.the_usual_weather') }}">The Usual Weather</a> </h1>
        <h2>What is the usual weather for...</h2>
        <form method="POST">
            {{ form.hidden_tag() }}
            <p class="form-label">{{ form.city.label }}:</p>{{ form.city }}
            <p class="form-label">{{ form.date.label }}:</p>{{ form.date(class="calendar") }}
            <br>
            <br>
            {{ form.submit(class="action-button") }}
        </form>
        <p><strong>Notes about entering the value for "city"</strong>:</p>
            <ul>
                <li>Be cautious with spelling - there's no autocorrect. If it's misspelled, then the submission won't go through.</li>
                <li>If state/province is not provided, it will default to the largest city of that name.</li>
                <ul>
                    <li>Entering <strong>"baltimore"</strong> (no state) will return <strong>"Baltimore, MD"</strong></li>
                    <li>Entering <strong>"baltimore, md"</strong> will return <strong>"Baltimore, MD"</strong></li>
                    <li>Entering <strong>"baltimore, oh"</strong> will return <strong>"Baltimore, Ohio"</strong> (yes, that's a real place)</li>
                </ul>
                <li>The city-validation checks against open-source mapping services, so if you enter "asdf", you might find somebody has created it as a place in some mapping service.</li>
            </ul>
            <p><strong>Note about date entry:</strong><p>
        <p> The year value is irrelevant. I chose a calendar date-entry form to avoid users entering an invalid date (Nov 31st, etc.) which would cause things to not work. Once you a pick a date, I just ignore the year value.</p>
        <p>Why are these important? See previous page for an overview of how the tool works.</p>
    </div>
{% endblock %}