base/gibbergen/views.py
from time import strftime
import markdown
from flask import Flask, Blueprint, render_template, request, session, redirect, url_for, flash
import json, random
from datetime import datetime
from os import getcwd
from flask_login import login_required, current_user
from base.lumberjack.views import lumberjack_do

cwd = getcwd()
gibbergen_blueprint = Blueprint('gibbergen', __name__, template_folder='templates/gibbergen')

clean_verb_path = f'{cwd}/gibbergen/data/ing_words_clean.json'
clean_tech_path = f'{cwd}/gibbergen/data/tech_terms_clean.json'


def get_verbs(path):
    with open(path) as json_verb_file:
        data = json.load(json_verb_file)
        json_verb_file.close()
        return data


def get_terms(path):
    with open(path) as json_tech_file:
        data = json.load(json_tech_file)
        json_tech_file.close()
        return data

def term_maker():
    """
    takes no input.
    returns a random term that sounds like something technical is happening
    <verb>ing the <technical noun>
    :return: text string
    """
    verbs = get_verbs(clean_verb_path)
    terms = get_terms(clean_tech_path)
    num_verbs = len(verbs)
    num_terms = len(terms)
    verb_choice = str(random.randint(1,num_verbs))
    term_choice = str(random.randint(1, num_terms))
    verbing = verbs[verb_choice]
    termicle = terms[term_choice]
    verbs = []
    terms = []
    gibberish = f'{verbing} the {termicle}...'
    return gibberish


@gibbergen_blueprint.route('/')
def gibbergen():
    term = term_maker()
    about_term = term_maker()
    with open (f'{cwd}/gibbergen/data/about.txt', 'r') as f:
        md_about = f.read()
        f.close()
        about = markdown.markdown(md_about)
    lumberjack_do(datetime.utcnow(), current_user, "gibbergen", f'generated "{term}" on main gibbergen page')
    return render_template('gibbergen_home.html', term=term, about=about, about_term=about_term)


@gibbergen_blueprint.route('/sampler')
@login_required
def gibbergen_sampler():
    term_list = []
    i = range(1, 10)
    for n in i:
        term = term_maker()
        term_list.append(term)
    lumberjack_do(datetime.utcnow(), current_user, "gibbergen", f'generated {term_list} on gibbergen sampler page')
    return render_template('gibbergen_sampler.html', terms=term_list)

#next:
#save term to a database and call an LLM to generate a made-up meaning for it
#create a way to browse the db entries
#for the sampler, allow the terms to be clicked for above functionality

base/gibbergen/templates/gibbergen/gibbergen-base.html
{% extends "base.html" %}
{% block title %}
    <title>Alex's Toolbox - GibberGen</title>
{% endblock %}
{% block additional_css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/gibbergen/gibbergen.css') }}" />
{% endblock %}
{% block body_class %}gibbergen-pages{% endblock %}

base/gibbergen/templates/gibbergen/gibbergen_home.html
{% extends "gibbergen-base.html" %}

{% block content %}
    <div class="default-container">
        <h1>GibberGen - The Gibberish Generator</h1>
        <h3>Your term is:</h3>
        <div class="hacker-console">
            <p class="term-text">{{ term }}</p>
        </div>

        <p>Reload to generate a new term. Click <a href="{{ url_for('gibbergen.gibbergen_sampler') }} ">here</a> to get 10 terms.</p>
        <p>{{ about|safe }}{{ about_term }}</p>
    </div>

{% endblock %}

base/gibbergen/templates/gibbergen/gibbergen_sampler.html
{% extends "gibbergen-base.html" %}

{% block content %}
    <div class="default-container">
    <h1>GibberGen - The Gibberish Generator</h1>
    <h3>Your terms are:</h3>
    <div class="hacker-console">
    <ul class="term-text">
        {% for term in terms %}
            <li>{{ term }}</li>
        {% endfor %}
    </ul>
    </div>
    <p>Reload to generate new terms.</p>
    </div>
{% endblock %}

base/gibbergen/templates/gibbergen/sampler.html
{% extends "gibbergen-base.html" %}

{% block content %}
    <div class="gibbergen-display">
    <h1>GibberGen - The Gibberish Generator</h1>
    <h3>Your terms are:</h3>
    <div class="hacker-console">
    <ul class="term-list">
        {% for term in terms %}
            <li>{{ term }}</li>
        {% endfor %}
    </ul>
    </div>
    <p>Reload to generate new terms.</p>
    </div>
{% endblock %}

base/gibbergen/templates/gibbergen/single_term.html
{% extends "base.html" %}
{% block title %}
    <title>Alex's Toolbox - GibberGen</title>
{% endblock %}

{% block content %}
    <h1>GibberGen - The Gibberish Generator</h1>
    <h3>Your term is:</h3>
    <p>{{ term }}</p>
    <p>Reload to generate a new term.</p>
{% endblock %}