base/users/views.py
from flask import current_app, Flask, Blueprint, render_template, request, session, redirect, url_for, flash, abort
from flask_login import login_user, login_required, logout_user, current_user
from base import app, db
from base.decorators import admin_required
from datetime import datetime, timedelta
from base.lumberjack.views import lumberjack_do
from base.models import User, Invitee
from base.users.forms import RegistrationForm, LoginForm, InviteForm, UnInviteForm
from werkzeug.security import generate_password_hash, check_password_hash


users_blueprint = Blueprint('users', __name__, template_folder='templates/users')

@users_blueprint.route('/', methods=['GET'])
def users():
    #basic home for users
    #add account management functions
    return render_template('users-home.html')

@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    #env variable allows me to toggle registration OPEN CLOSED INVITE ONLY
    registration_mode = current_app.config['REGISTRATION_MODE']
    bouncer = False
    if registration_mode == "CLOSED":
        abort(423)
    elif registration_mode == "INVITE_ONLY":
        # bouncer tells the template to display a warning and checks if you're on the list
        bouncer = True
    form = RegistrationForm()
    if form.validate_on_submit():
        # check if email exists
        if User.check_email(email=form.email.data.lower()):
            flash('This Email is already registered.', "warning")
            lumberjack_do(datetime.utcnow(), current_user, "users",
                          f"Somebody tried to register as {form.email.data}")
            return redirect(url_for('users.register'))
        #check if the submitted email is on the approved list
        # if bouncer:

        # check if username exists
        elif User.check_username(username=form.username.data.lower()):
            flash('This username is already taken.', "warning")
            lumberjack_do(datetime.utcnow(), current_user, "users",
                          f"Somebody tried to register as {form.username.data}")
            return redirect(url_for('users.register'))

        else:
            user = User(username=form.username.data,
                        email=form.email.data.lower(),
                        password=form.password.data,
                        registration_date=datetime.utcnow())
            # add registration date
            db.session.add(user)
            db.session.commit()
            lumberjack_do(datetime.utcnow(), current_user, "users",
                          f"{form.email.data} registered as {form.username.data}")
            flash('Thank you for registering. You can now login.', "success")
            return redirect(url_for('users.login'))
    if form.errors:
        for field, errors in form.errors.items():
            for error in errors:
                flash(f"{field} error: {error}", "warning")
    return render_template('users-register.html', form=form, bouncer=bouncer)



@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        # force submitted email to lowercase
        email = form.email.data.lower()
        user = db.session.execute(db.select(User).filter_by(email=email)).scalar()
        #check if user is allowed to log in or if they're banned
        if user.is_banned():
            flash('You are banned. Go on, git!', "warning")
            return redirect(url_for('users.login'))
        if User.check_email(email=email) and user.check_password(form.password.data) and user is not None:
            # here we are checking for ENV admins and updating the db
            if user.sync_admin_status():
                db.session.commit()
            #handling the login and enforcing the default session duration
            login_user(user, remember=True)
            # update last login date
            latest_login_date = datetime.utcnow()
            db.session.execute(db.update(User).where(User.id == user.id).values(last_login_date=latest_login_date))
            db.session.commit()
            flash('You have been logged in.', "success")
            #logging the login
            lumberjack_do(datetime.utcnow(), current_user, "users", "User Logged In")
            #check if pwd reset is required and redirect to that page
            next = request.args.get('next')
            if next == None or not next[0]=='/':
                next = url_for('users.welcome')
            return redirect(next)
        else:
            flash('Invalid username or password', "warning")
            return redirect(url_for('users.login'))
    return render_template('users-login.html', form=form)


#setting global session timeout
@app.before_request
def check_session_timeout():
    if current_user.is_authenticated:
        if current_user.banned:
            logout_user()
            flash('You are banned. Go on, git!', "warning")
            return redirect(url_for('users.login'))
        last_login = current_user.last_login_date
        if last_login:
            if datetime.utcnow() - last_login > timedelta(hours=4):
                lumberjack_do(datetime.utcnow(), current_user, "user admin", "user session auto-expired")
                logout_user()
                return redirect(url_for('users.login'))


@users_blueprint.route('/welcome', methods=['GET', 'POST'])
@login_required
def welcome():
    return render_template('users-welcome.html')

@users_blueprint.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    lumberjack_do(datetime.utcnow(), current_user, "users", "User Logged Out")
    logout_user()
    flash('You have been logged out.')
    return redirect(url_for('index'))


#reset pwd

#profile
#a page where users can see their past activity


#admin only

@users_blueprint.route('/lookup-users', methods=['GET', 'POST'])
@login_required
@admin_required
def lookup_users():
    #form submission for lookup
    # by id
        # if exists - opens manage user page

    # by email
        # if exists - opens manage user page

    # by username
        # if exists - opens manage user page

    #returns result as users and feeds to the same table as the GET

    #If not POST
    #lists all
    user_base = db.session.execute(db.select(User).order_by(User.email.desc())).scalars()
    users = [user.to_dict() for user in user_base]

    return render_template('users-lookup_users.html', users=users)


@users_blueprint.route('/invite-user', methods=['GET', 'POST'])
@login_required
@admin_required
def invite_user():
    #shows the invitee list
    #adds an email to a list of approved registrants
    approved_list = db.session.execute(db.select(Invitee).order_by(Invitee.email.desc())).scalars()
    approved_list_clean = [invitee.to_dict()['email'] for invitee in approved_list]
    form = InviteForm()
    if request.method == 'POST':
        if form.submit.data and form.validate_on_submit():
            email = form.email.data.lower()
            if email in approved_list_clean:
                flash('This email is already invited.', "warning")
                return redirect(url_for('users.invite_user'))
            db.session.execute(db.insert(Invitee).values(email=email))
            db.session.commit()
            lumberjack_do(datetime.utcnow(), current_user, "users", f"{email} was added to the approved list")
            flash(f'{email} has been added to the approved list.', "success")
            return redirect(url_for('users.invite_user'))
    return render_template('users-invite_list.html', approved_list_clean=approved_list_clean, form=form)


@users_blueprint.route('/uninvite-user', methods=['GET', 'POST'])
@login_required
@admin_required
def uninvite_user():
    #shows the invitee list
    #removes an email from a list of approved registrants
    approved_list = db.session.execute(db.select(Invitee).order_by(Invitee.email.desc())).scalars()
    approved_list_clean = [invitee.to_dict()['email'] for invitee in approved_list]
    form = UnInviteForm()
    if request.method == 'POST':
        if form.submit.data and form.validate_on_submit():
            email = form.email.data.lower()
            if email not in approved_list_clean:
                flash('This email is not yet invited.', "warning")
                return redirect(url_for('users.uninvite_user'))
            to_delete = db.one_or_404(db.select(Invitee).filter_by(email=email))
            db.session.delete(to_delete)
            db.session.commit()
            lumberjack_do(datetime.utcnow(), current_user, "users", f"{email} was removed from the approved list")
            flash(f'{email} was removed from the approved list.', "success")
            return redirect(url_for('users.uninvite_user'))
    return render_template('users-invite_list.html', approved_list_clean=approved_list_clean, form=form)

@users_blueprint.route('/manage-user/<int:user_id>', methods=['GET', 'POST'])
@login_required
@admin_required
#make these separate endpoints with a popup "Are you sure?"
def manage_user(user_id):
    user_data = db.session.execute(db.select(User).filter_by(id=user_id)).scalar()
    # check against ENV admins and stop
    user = user_data.to_dict()
    #options:
    if request.method == 'POST':
        user_id = request.form.get('user_id')
        user_to_modify = db.session.query(User).filter_by(id=user_id).scalar()
        #protecting the webmaster account (ENV admin) from modification
        if user_to_modify.is_webmaster():
            flash("You can't modify a webmaster account!", "warning")
            return redirect(url_for('users.manage_user', user_id=user_id))
        action = request.form.get('action')
        if action == 'ban':
            # Ban user logic
            user_to_modify.ban_user()
            db.session.commit()
            lumberjack_do(datetime.utcnow(), current_user, "users", f"{user_to_modify.email} was banned")

base/users/templates/users/login.html
{% extends "user-base.html" %}

{% block content %}
    <div class="default-container">
    <form method="POST">
    {{ form.hidden_tag() }}
    <p class="form-label">{{ form.email.label }}:</p>{{ form.email }}
        <br>
    <p class="form-label">{{ form.password.label }}:</p>{{ form.password }}
        <br>
        <br>
    {{ form.submit(class="action-button") }}
    </form>
    </div>
{% endblock %}

base/users/templates/users/register.html
{% extends "user-base.html" %}

{% block content %}
    <div class="default-container">
        <form method="POST">
        {{ form.hidden_tag() }}
        <p class="form-label">{{ form.email.label }}:</p>{{ form.email }}
            <br>
        <p class="form-label">{{ form.username.label }}:</p>{{ form.username }}
            <br>
        <p class="form-label">{{ form.password.label }}:</p>{{ form.password }}
            <br>
        <p class="form-label">{{ form.pass_confirm.label }}:</p>{{ form.pass_confirm }}
            <br>
            <br>
        {{ form.submit(class="action-button") }}
    </form>
    </div>
{% endblock %}

base/users/templates/users/show_user.html
{% extends "user-base.html" %}

{% block content %}
    <div class="default-container">
    <p>{{ user }}</p>
    </div>
{% endblock %}

base/users/templates/users/user-base.html
{% extends "base.html" %}

{% block additional_css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/users/users.css') }}" />
{% endblock %}

{% block body_class %}user-pages{% endblock %}

base/users/templates/users/users-base.html
{% extends "base.html" %}

{% block additional_css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/users/users.css') }}" />
{% endblock %}

{% block body_class %}user-pages{% endblock %}

base/users/templates/users/users-home.html
{% extends "users-base.html" %}

{% block content %}
    <div class="default-container">
    <ul>
        {% if current_user.is_authenticated %}
        <li><a class="user-page-link" href="{{ url_for('users.logout') }}">Log Out</a></li>
        {% else %}
        <li><a class="user-page-link" href="{{ url_for('users.register') }}">Register</a></li>
        <li><a class="user-page-link" href="{{ url_for('users.login') }}">Login</a></li>
        {% endif %}
    </ul>
    </div>
{% endblock %}

base/users/templates/users/users-invite_list.html
{% extends "users-base.html" %}

{% block content %}
    <div class="default-container">
        <div class="bouncer-list">
        <h2>Approved emails:</h2>
            <ul>
            {% for invitee in approved_list_clean %}
            <li>{{invitee}}</li>
            {% endfor %}
        </ul>
        </div>
    <div class="invite-container">
        <form method="POST">
            {{ form.hidden_tag() }}
            <p class="form-label">{{ form.email.label }}:</p><p>{{ form.email }}</p>
            <br>
            {{ form.submit(class="action-button") }}
        </form>
    </div>

    </div>
{% endblock %}

base/users/templates/users/users-login.html
{% extends "users-base.html" %}

{% block content %}
    <div class="default-container">
    <form method="POST">
    {{ form.hidden_tag() }}
    <p class="form-label">{{ form.email.label }}:</p>{{ form.email }}
        <br>
    <p class="form-label">{{ form.password.label }}:</p>{{ form.password }}
        <br>
        <br>
    {{ form.submit(class="action-button") }}
    </form>
    </div>
{% endblock %}

base/users/templates/users/users-lookup_users.html
{% extends "users-base.html" %}

{% block content %}
    <div class="user-admin-display">
    <h1>User Administration</h1>
    <div class="user-admin-table">
        <table>
            <thead>
                <tr>
                    <th>Username</th>
                    <th>Email Address</th>
                    <th>User ID #</th>
                    <th>Admin Access</th>
                    <th>Registration Date</th>
                    <th>Last Login</th>
                    <th>Banned?</th>
                    <th>Temp Password</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
            {% if users %}
                {% for user in users %}
                    <tr>
                        <td>{{ user.username }}</td>
                        <td>{{ user.email }}</td>
                        <td>{{ user.id }}</td>
                        <td>{{ user.is_admin }}</td>
                        <td>{{ user.registration_date }}</td>
                        <td>{{ user.last_login }}</td>
                        <td>{{ user.banned }}</td>
                        <td>{{ user.expired_password }}</td>
                        <td><a href="{{ url_for('users.manage_user', user_id=user.id) }}">Manage User</a></td>
                    </tr>
                {% endfor %}
            {% elif user %}
                    <tr>
                        <td>{{ user.username }}</td>
                        <td>{{ user.email }}</td>
                        <td>{{ user.id }}</td>
                        <td>{{ user.is_admin }}</td>
                        <td>{{ user.registration_date }}</td>
                        <td>{{ user.last_login }}</td>
                        <td>{{ user.banned }}</td>
                        <td>{{ user.expired_password }}</td>
                        <td><a href="{{ url_for('users.lookup_users') }}">Back to all users...</a> </td>
                    </tr>
            {% endif %}
        </table>
    </div>
    {% block action %}
    {% endblock %}
    </div>
{% endblock %}

base/users/templates/users/users-register.html
{% extends "users-base.html" %}

{% block content %}
    <div class="default-container">
    <h1>User Registration</h1>
    {% if bouncer %}
        <p class="registration-warning">Registration is currently in Invite Only mode. If your email address is not on Alex's approved list, your registration will be rejected.</p>
        <p>This site is a hobby/portfolio project, access is restricted to save hosting costs.</p>
    {% endif %}
        <form method="POST">
        {{ form.hidden_tag() }}
        <p class="form-label">{{ form.email.label }}:</p>{{ form.email }}
            <br>
        <p class="form-label">{{ form.username.label }}:</p>{{ form.username }}
            <br>
        <p class="form-label">{{ form.password.label }}:</p>{{ form.password }}
            <br>
        <p class="form-label">{{ form.pass_confirm.label }}:</p>{{ form.pass_confirm }}
            <br>
            <br>
        {{ form.submit(class="action-button") }}
    </form>
    </div>
{% endblock %}

base/users/templates/users/users-user_detail.html
{% extends "users-lookup_users.html" %}

{% block action %}
    <div class="user-actions">
    <form method="POST">
        <input type="hidden" name="user_id" value="{{ user.id }}">
        {% if not user.banned %}
        <button type="submit" name="action" value="ban">Ban User</button>
        {% else %}
        <button type="submit" name="action" value="unban">Un-Ban User</button>
        {% endif %}
        <button type="submit" name="action" value="reset_password">Force Password Reset</button>
        <button type="submit" name="action" value="delete">Delete User</button>
        {% if not user.is_admin %}
        <button type="submit" name="action" value="promote">Promote to Admin</button>
        {% else %}
        <button type="submit" name="action" value="demote">Demote to User</button>
        {% endif %}
    </form>
    </div>
{% endblock %}

base/users/templates/users/users-welcome.html
{% extends "users-base.html" %}

{% block content %}
    <div class="default-container">
        <p>Login successful</p>
    </div>
{% endblock %}

base/users/templates/users/users.html
{% extends "user-base.html" %}

{% block content %}
    <div class="default-container">
    <ul>
        {% if current_user.is_authenticated %}
        <li><a class="user-page-link" href="{{ url_for('users.logout') }}">Log Out</a></li>
        {% else %}
        <li><a class="user-page-link" href="{{ url_for('users.register') }}">Register</a></li>
        <li><a class="user-page-link" href="{{ url_for('users.login') }}">Login</a></li>
        {% endif %}
    </ul>
    </div>
{% endblock %}

base/users/templates/users/welcome.html
{% extends "user-base.html" %}

{% block content %}
    <div class="default-container">
        <p>Login successful</p>
    </div>
{% endblock %}